import { Actor, Linkage, Program } from '../types';

/**
 * Email Service - Composes professional linkage proposal emails
 * Uses mailto: links (100% free, no API keys, no external services)
 * The admin's email client opens with a pre-composed email ready to send.
 */

interface EmailContext {
  linkage: Linkage;
  source: Actor;
  target: Actor;
  program?: Program;
  adminEmail: string;
  appUrl: string;
}

/**
 * Generate the respond URL for accept/reject actions
 */
export function getRespondUrl(appUrl: string, linkageId: string, party: 'source' | 'target'): string {
  const url = new URL(appUrl);
  url.searchParams.set('action', 'respond');
  url.searchParams.set('linkageId', linkageId);
  url.searchParams.set('party', party);
  return url.toString();
}

/**
 * Compose the email body for a specific party (source or target)
 */
function composeEmailBody(ctx: EmailContext, recipientRole: 'source' | 'target'): string {
  const { source, target, linkage, program } = ctx;
  const recipient = recipientRole === 'source' ? source : target;
  const otherParty = recipientRole === 'source' ? target : source;
  const recipientLabel = recipientRole === 'source' ? 'Source Entity' : 'Target Entity';
  const otherLabel = recipientRole === 'source' ? 'Proposed Match' : 'Proposing Entity';
  
  const respondUrl = getRespondUrl(ctx.appUrl, linkage.id, recipientRole);

  let body = `Dear ${recipient.name},\n\n`;
  body += `We are pleased to inform you about a new ecosystem partnership proposal generated by the NexusCore AI Matching Engine.\n\n`;
  body += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  body += `LINKAGE PROPOSAL DETAILS\n`;
  body += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  body += `Relationship Type: ${linkage.type}\n`;
  body += `AI Confidence Score: ${(linkage.engagementScore * 100).toFixed(1)}%\n`;
  if (program) {
    body += `Associated Programme: ${program.title}\n`;
  }
  body += `\n`;

  body += `── YOUR PROFILE (${recipientLabel.toUpperCase()}) ──\n`;
  body += `Name: ${recipient.name}\n`;
  body += `Type: ${recipient.type.toUpperCase()}\n`;
  body += `Sector: ${recipient.subType || 'N/A'}\n`;
  body += `Region: ${recipient.region}\n`;
  body += `About: ${recipient.bio}\n`;
  if (recipient.resources) {
    body += `Resources: ${recipient.resources}\n`;
  }
  body += `\n`;

  body += `── PROPOSED MATCH (${otherLabel.toUpperCase()}) ──\n`;
  body += `Name: ${otherParty.name}\n`;
  body += `Type: ${otherParty.type.toUpperCase()}\n`;
  body += `Sector: ${otherParty.subType || 'N/A'}\n`;
  body += `Region: ${otherParty.region}\n`;
  body += `About: ${otherParty.bio}\n`;
  if (otherParty.resources) {
    body += `Resources: ${otherParty.resources}\n`;
  }
  body += `\n`;

  body += `── AI JUSTIFICATION ──\n`;
  body += `${linkage.aiJustification}\n\n`;
  
  body += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  body += `ACTION REQUIRED\n`;
  body += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  body += `Please review this proposal and respond by clicking one of the options below:\n\n`;
  body += `[ ACCEPT PROPOSAL ]\n`;
  body += `${respondUrl}&decision=accepted\n\n`;
  body += `[ REJECT PROPOSAL ]\n`;
  body += `${respondUrl}&decision=rejected\n\n`;
  body += `Or view full details and respond here:\n`;
  body += `${respondUrl}\n\n`;
  body += `Both parties must accept for the linkage to be activated.\n\n`;
  
  body += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  body += `This email was sent by ${ctx.adminEmail} via NexusCore Ecosystem OS.\n`;
  body += `Linkage ID: ${linkage.id}\n`;

  return body;
}

/**
 * Compose the email subject line
 */
function composeSubject(ctx: EmailContext, recipientRole: 'source' | 'target'): string {
  const { source, target } = ctx;
  return `[NexusCore] Partnership Proposal: ${source.name} ↔ ${target.name} — Action Required`;
}

/**
 * Open mailto: link to send email to a specific party
 */
export function openMailtoForParty(ctx: EmailContext, recipientRole: 'source' | 'target'): void {
  const recipient = recipientRole === 'source' ? ctx.source : ctx.target;
  const recipientEmail = recipient.email;
  
  if (!recipientEmail) {
    alert(`No email address found for ${recipient.name}. Please update the entity's contact email.`);
    return;
  }

  const subject = composeSubject(ctx, recipientRole);
  const body = composeEmailBody(ctx, recipientRole);
  
  const mailtoUrl = `mailto:${encodeURIComponent(recipientEmail)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  
  window.open(mailtoUrl, '_blank');
}

/**
 * Open mailto: links for BOTH parties at once
 */
export function openMailtoForBothParties(ctx: EmailContext): void {
  openMailtoForParty(ctx, 'source');
  // Small delay so the email client can handle two opens
  setTimeout(() => {
    openMailtoForParty(ctx, 'target');
  }, 500);
}

/**
 * Get a preview of the email content (for display in the modal)
 */
export function getEmailPreview(ctx: EmailContext, recipientRole: 'source' | 'target'): {
  to: string;
  subject: string;
  body: string;
} {
  const recipient = recipientRole === 'source' ? ctx.source : ctx.target;
  return {
    to: recipient.email || '(no email set)',
    subject: composeSubject(ctx, recipientRole),
    body: composeEmailBody(ctx, recipientRole),
  };
}
